language: php
php:
  - 5.4

before_script:
  - "mkdir $HOME/git-test && cd $HOME/git-test && git init"
  - "mkdir $HOME/git-test-path && cd $HOME/git-test-path && git init"

script:
  # Test installation from current directory.
  - "cd $HOME/git-test && $(which php) $TRAVIS_BUILD_DIR/commit-msg INSTALL && test $HOME/git-test/.git/hooks/commit-msg"
  # Test installation into specified directory.
  - "cd $HOME/git-test-path && $(which php) $TRAVIS_BUILD_DIR/commit-msg INSTALL $HOME/git-test-path && test $HOME/git-test-path/.git/hooks/commit-msg"
  # Run unit tests.
  - $(which php) $TRAVIS_BUILD_DIR/commit-msg SELFTEST
